# Generated by Django 2.2.7 on 2019-11-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Canais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiro', models.CharField(max_length=50)),
                ('segundo', models.CharField(max_length=50)),
                ('terceiro', models.CharField(max_length=50)),
            ],
        ),
    ]
