# Generated by Django 2.2.7 on 2019-11-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiro', models.CharField(max_length=100)),
                ('segunda', models.CharField(max_length=100)),
                ('terceira', models.CharField(max_length=100)),
            ],
        ),
    ]
