# Generated by Django 2.2.7 on 2019-11-13 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_frases'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frases',
            old_name='primeiro',
            new_name='frase1',
        ),
        migrations.RenameField(
            model_name='frases',
            old_name='segunda',
            new_name='frase2',
        ),
        migrations.RenameField(
            model_name='frases',
            old_name='terceira',
            new_name='frase3',
        ),
    ]
