# Generated by Django 2.2.7 on 2019-11-13 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191113_1206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frases',
            old_name='frase1',
            new_name='frase',
        ),
        migrations.RemoveField(
            model_name='canais',
            name='segundo',
        ),
        migrations.RemoveField(
            model_name='canais',
            name='terceiro',
        ),
        migrations.RemoveField(
            model_name='frases',
            name='frase2',
        ),
        migrations.RemoveField(
            model_name='frases',
            name='frase3',
        ),
    ]
